### ISSUE TITLE
New npm Release

### ISSUE THREAD

**Issue by tycrimm** [Kendy205/astro-og-image#4]
Hey Kendy! Was hoping you could publish a new version of the package to npm when you have a moment?

Also happy to help however I can - just let me know. Thank you!

**Comment by tomaskebrle** [comment]
Sorry completely forgot you need to do that, after making changes. I should set up some sort of CI pipeline, although that is maybe unnecessary for such a small project

**Comment by tycrimm** [comment]
Thank you!
