### ISSUE TITLE
How to use without mdx

### ISSUE THREAD

**Issue by preetamslot** [Kendy205/astro-og-image#8]
I am using storyblok api with getStaticPaths.
How can I generate the og-images without md files?

**Comment by tomaskebrle** [comment]
Yeah I am not sure if this is currently possible, altough if you use some kind of layout, i think it could work. I can try to make it work if you would provide a code example on how you have your site setup since I have never worked with storyblok. Also I'm currently quite busy with school, so I can maybe take a look on thursday.

**Comment by preetamslot** [comment]
Take your time, no hurry :)
Here is the documentation on storyblok:
https://github.com/storyblok/storyblok-astro
it just uses the getStaticPaths to create all routes.

It would be great if we could use the og image as a component. so we can pass all data and images and style it.

Thanks again!

**Comment by tomaskebrle** [comment]
https://stackblitz.com/edit/astro-sdk-demo-txt2qd?file=src/layouts/BaseLayout.astro
Just by looking at it, this should make it work however, I was not able to confirm it works

But you just need to pass the slug back to BaseLayout

```html
<!-- [slug].astro -->
<BaseLayout slug={slug}>
```

add meta tags to the head
```html 
<!-- BaseLayout.astro -->
<meta
  property="og:image"
  content={slug !== undefined
    ? `/assets/${slug}.png`
    : `/assets/fallback-image.png`}
/>
<meta
  property="twitter:image"
  content={slug !== undefined
    ? `/assets/${slug}.png`
    : `/assets/fallback-image.png`}
/>
```

and change the `astro.config.mjs`

```js
astroOGImage({
  config: {
    path: "/pages",
  },
}),
```

**Comment by tomaskebrle** [comment]
Should hopefully work now. But you need to install the beta version `npm i astro-og-image@1.0.8`
